version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - rabbitmq
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
      MESSAGE_QUEUE: amqp://rabbitmq
    ports:
      - "3000:3000"
    # command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"


      #context: .
      #dockerfile: backend/Dockerfile